package com.ripenapps.adoreandroid.preferences

const val IS_LOGIN = "is_login"
const val IS_WELCOME_DONE = "isWelcomeDone"
const val TOKEN = "token"
const val FCM_TOKEN = "fcmToken"
const val DATA = "data"
const val NAME = "name"
const val PROFILE = "profile"
const val EMAIL = "email"
const val USER_NAME = "user_name"
const val USER_ID="user_id"
const val IS_USER_SUBSCRIBED="is_user_subscribed"
const val PLAN_EXPIRE_DATE="plan_expire_date"
const val HAS_USER_SUBSCRIBED_BEFORE="has_user_subscribed_before"
const val COUNTRY="country"
const val CITY="city"
const val SAVED_ADDRESS="saved_address"
const val SAVED_LAT="saved_lat"
const val SAVED_LONG="saved_long"
const val SOCIAL_TYPE = "social_type"
const val SELECTED_LANGUAGE_CODE="selected_language_code"
const val PLAN_AMOUNT=""
const val IS_UPDATE_LATER_PRESSED="0"

